#!/usr/bin/env python3
"""Build the evidence package for Reviewer 6, item R6-02.

The flat-text results are reused from the leakage-audited R3-03 five-fold
experiment.  The InLegalLlama rows are recomputed from per-case generations:
unparseable outputs are abstentions and count as errors in the primary metrics.
Parsed-only performance is retained under the explicit name ``selective``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
PAPER_TESTS = HERE.parents[1]
REPO = HERE.parents[2]
R3_OUTPUTS = PAPER_TESTS / "codes" / "R3_03_non_llm_baselines" / "outputs"
LLM_OUTPUTS = REPO / "model comparison" / "outputs"
HGT_KFOLD = (
    REPO
    / "section_GNN/outputs/ablations/entity_resolved_data/cross_bucket_total_dataset/models"
    / "ablation_entity_resolved_section_sep_lr_decay_cross_bucket_kfold/kfold/kfold_summary.json"
)
LLM_RUNS = {
    "InLegalLlama (CPT)": (
        "lnlproc_inlegalllama_entity_resolved_section_sep_lr_decay_cross_bucket_fold00_test"
    ),
    "InLegalLlama (SFT)": (
        "lnlproc_inlegalllama_sft_pred_only_original_prompt_cross_bucket_fold00"
    ),
}
LABELS = ("-1", "1")
OUTPUTS = HERE / "outputs"


def per_label(rows: list[dict[str, Any]], label: str) -> dict[str, float | int]:
    tp = sum(r["true_label"] == label and r.get("predicted_label") == label for r in rows)
    fp = sum(r["true_label"] != label and r.get("predicted_label") == label for r in rows)
    fn = sum(r["true_label"] == label and r.get("predicted_label") != label for r in rows)
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return {"tp": tp, "fp": fp, "fn": fn, "precision": precision, "recall": recall, "f1": f1}


def evaluate_llm(run_dir: Path) -> dict[str, Any]:
    rows = []
    with (run_dir / "combined_predictions.jsonl").open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            if str(row.get("true_label")) in LABELS:
                row["true_label"] = str(row["true_label"])
                prediction = row.get("predicted_label")
                row["predicted_label"] = str(prediction) if prediction is not None else None
                rows.append(row)

    answered = [r for r in rows if r.get("predicted_label") in LABELS]
    correct = sum(r["true_label"] == r.get("predicted_label") for r in rows)
    strict = {label: per_label(rows, label) for label in LABELS}
    selective = {label: per_label(answered, label) for label in LABELS}
    result = {
        "n": len(rows),
        "answered": len(answered),
        "abstained": len(rows) - len(answered),
        "coverage": len(answered) / len(rows),
        "accuracy": correct / len(rows),
        "macro_f1": sum(v["f1"] for v in strict.values()) / len(LABELS),
        "selective_accuracy": correct / len(answered),
        "selective_macro_f1": sum(v["f1"] for v in selective.values()) / len(LABELS),
        "per_label": strict,
        "selective_per_label": selective,
        "policy": "full denominator; unparseable generations are abstentions counted as errors",
    }
    recorded = json.loads((run_dir / "metrics.json").read_text())
    for key in ("accuracy", "macro_f1", "selective_accuracy", "selective_macro_f1", "coverage"):
        if abs(result[key] - recorded[key]) > 1e-12:
            raise AssertionError(f"{run_dir.name}: recomputed {key} differs from metrics.json")
    return result


def latex(payload: dict[str, Any]) -> str:
    b = payload["flat_text"]
    h = payload["hgt"]
    cpt = payload["llm"]["InLegalLlama (CPT)"]
    sft = payload["llm"]["InLegalLlama (SFT)"]
    return rf"""% R6-02: genuine flat-text baselines and coverage-aware LLM evaluation.
% Generated by Paper_Additional_Tests/codes/R6_02_flat_text_llm_denominator/evaluate_r6_02.py
\begin{{table}}[!htbp]
\centering
\caption{{Flat-text and generative baselines. Classical models and \method{{}} use the same five case-level folds. LLM results use fold 0 ($n=14{{,}}363$); their primary metrics use all cases, counting an unparseable generation as an incorrect abstention. Parentheses give parsed-only selective accuracy/macro-F1.}}
\label{{tab:r6-02-baselines}}
\setlength{{\tabcolsep}}{{4pt}}
\scriptsize
\begin{{adjustbox}}{{max width=\textwidth}}
\begin{{tabular}}{{l l r r r l}}
\toprule
Model & Input/evaluation & Coverage & Accuracy (\%) & Macro-F1 & Protocol \\
\midrule
Majority class & no features & 100.0\% & {100*b['majority']['accuracy']:.2f} & {b['majority']['macro_f1']:.4f} & five-fold mean \\
Linear SVM & sanitized flat TF--IDF & 100.0\% & \textbf{{{100*b['svm']['accuracy']:.2f}}} & \textbf{{{b['svm']['macro_f1']:.4f}}} & five-fold mean \\
Logistic regression & sanitized flat TF--IDF & 100.0\% & {100*b['logreg']['accuracy']:.2f} & {b['logreg']['macro_f1']:.4f} & five-fold mean \\
\method{{}} (HGT) & heterogeneous graph & 100.0\% & {100*h['accuracy']:.2f} & {h['macro_f1']:.4f} & five-fold mean \\
\midrule
InLegalLlama (CPT) & full denominator & {100*cpt['coverage']:.1f}\% & {100*cpt['accuracy']:.2f} ({100*cpt['selective_accuracy']:.2f}) & {cpt['macro_f1']:.4f} ({cpt['selective_macro_f1']:.4f}) & one held-out fold \\
InLegalLlama (SFT) & full denominator & {100*sft['coverage']:.1f}\% & {100*sft['accuracy']:.2f} ({100*sft['selective_accuracy']:.2f}) & {sft['macro_f1']:.4f} ({sft['selective_macro_f1']:.4f}) & one held-out fold \\
\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\end{{table}}
"""


def report(payload: dict[str, Any]) -> str:
    b = payload["flat_text"]
    h = payload["hgt"]
    cpt = payload["llm"]["InLegalLlama (CPT)"]
    sft = payload["llm"]["InLegalLlama (SFT)"]
    return f"""# R6-02 — flat-text baseline and corrected InLegalLlama denominator

> Reviewer 6: the text-only ablation is still an HGT case-star graph, and the
> InLegalLlama accuracy is computed only on its parseable subset.

## Resolution

The first point is resolved with genuine flat-document classifiers on the same 71,813 cases
and the same five case-level folds as the HGT. Inputs contain only the retained preamble,
facts, and argument text. The TF–IDF pipeline removes mask artifacts and direct operative-outcome
vocabulary, fits its vectorizer on training rows only, selects regularization on validation
macro-F1, and evaluates the held-out test rows once.

| Model | Accuracy | Macro-F1 | Difference from HGT |
|---|---:|---:|---:|
| Majority class | {100*b['majority']['accuracy']:.2f}% | {b['majority']['macro_f1']:.4f} | {100*(b['majority']['accuracy']-h['accuracy']):+.2f} pp |
| Linear SVM, sanitized TF–IDF | **{100*b['svm']['accuracy']:.2f}%** | **{b['svm']['macro_f1']:.4f}** | **{100*(b['svm']['accuracy']-h['accuracy']):+.2f} pp** |
| Logistic regression, sanitized TF–IDF | {100*b['logreg']['accuracy']:.2f}% | {b['logreg']['macro_f1']:.4f} | {100*(b['logreg']['accuracy']-h['accuracy']):+.2f} pp |
| LegalGraph-LJP (HGT) | {100*h['accuracy']:.2f}% | {h['macro_f1']:.4f} | — |

The result changes the paper's conclusion: the strongest flat-text baseline exceeds HGT by
{100*(b['svm']['accuracy']-h['accuracy']):.2f} accuracy points and {b['svm']['macro_f1']-h['macro_f1']:.4f} macro-F1. The revision therefore
does not claim a predictive advantage over flat text; it frames the graph's contribution as
explicit typed structure and intervention-based auditability.

For InLegalLlama, an unparseable generation is now an abstention and is counted as an error in
the primary full-denominator metrics. Parsed-only performance is retained only as a selective
diagnostic:

| Model | n | Coverage | Full-denominator accuracy / macro-F1 | Parsed-only diagnostic |
|---|---:|---:|---:|---:|
| InLegalLlama (CPT) | {cpt['n']:,} | {100*cpt['coverage']:.1f}% | **{100*cpt['accuracy']:.2f}% / {cpt['macro_f1']:.4f}** | {100*cpt['selective_accuracy']:.2f}% / {cpt['selective_macro_f1']:.4f} |
| InLegalLlama (SFT) | {sft['n']:,} | {100*sft['coverage']:.1f}% | **{100*sft['accuracy']:.2f}% / {sft['macro_f1']:.4f}** | {100*sft['selective_accuracy']:.2f}% / {sft['selective_macro_f1']:.4f} |

The LLM runs cover only fold 0, whereas the flat-text and HGT values are five-fold means. The
revision states this explicitly and avoids treating the operational zero-shot run as an
exhaustive or fine-tuned LLM comparison.

## Artifacts and paper changes

- `outputs/r6_02_results.json`: machine-readable recomputation and provenance.
- `outputs/table_r6_02.tex`: drop-in table with coverage and both metric policies.
- `../../../../8pg_paper.tex`: abstract, results table/text, limitations, and conclusion revised.
- `../../../../model comparison/summarize_inlegalllama.py`: primary metrics now use the full denominator.
"""


def main() -> None:
    summary = json.loads((R3_OUTPUTS / "baselines_summary.json").read_text())
    baselines = summary["baselines"]
    hgt = json.loads(HGT_KFOLD.read_text())["aggregate"]
    payload = {
        "task_id": "R6-02",
        "status": "resolved",
        "flat_text": {
            "n": summary["n_cases"],
            "folds": summary["k"],
            "majority": {
                "accuracy": baselines["B0_majority"]["aggregate"]["accuracy_mean"],
                "macro_f1": baselines["B0_majority"]["aggregate"]["macro_f1_mean"],
            },
            "svm": {
                "accuracy": baselines["B3_svm_tfidf"]["aggregate"]["accuracy_mean"],
                "macro_f1": baselines["B3_svm_tfidf"]["aggregate"]["macro_f1_mean"],
            },
            "logreg": {
                "accuracy": baselines["B4_logreg_tfidf"]["aggregate"]["accuracy_mean"],
                "macro_f1": baselines["B4_logreg_tfidf"]["aggregate"]["macro_f1_mean"],
            },
            "source": str(R3_OUTPUTS / "baselines_summary.json"),
        },
        "hgt": {
            "accuracy": hgt["accuracy_mean"],
            "macro_f1": hgt["macro_f1_mean"],
            "source": str(HGT_KFOLD),
        },
        "llm": {
            label: evaluate_llm(LLM_OUTPUTS / directory)
            for label, directory in LLM_RUNS.items()
        },
    }
    OUTPUTS.mkdir(exist_ok=True)
    (OUTPUTS / "r6_02_results.json").write_text(json.dumps(payload, indent=2) + "\n")
    (OUTPUTS / "table_r6_02.tex").write_text(latex(payload))
    (OUTPUTS / "report_r6_02.md").write_text(report(payload))
    print(f"wrote R6-02 evidence package to {OUTPUTS}")


if __name__ == "__main__":
    main()
