#!/usr/bin/env python3
"""Turn the R3-03 baseline sweep into a LaTeX table and a rebuttal-ready report.

Reads three sources, none of which are re-run:
  * this study's ``outputs/baselines_summary.json``;
  * the HGT run's ``kfold_summary.json`` (the published 80.63 / 0.8002);
  * the InLegalLlama runs' ``metrics.json`` under ``model comparison/outputs``.

The reviewer asked specifically for the *absolute* improvement over a trivial
baseline, so the table reports Delta columns against the majority-class row as
well as against HGT.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parents[2]
_SECTION_GNN = _REPO / "section_GNN"
REFERENCE_KFOLD = (
    _SECTION_GNN
    / "outputs/ablations/entity_resolved_data/cross_bucket_total_dataset/models"
    / "ablation_entity_resolved_section_sep_lr_decay_cross_bucket_kfold/kfold"
)
LLM_OUTPUTS = _REPO / "model comparison" / "outputs"
LLM_RUNS = {
    "InLegalLlama (CPT)": "lnlproc_inlegalllama_entity_resolved_section_sep_lr_decay_cross_bucket_fold00_test",
    "InLegalLlama (SFT)": "lnlproc_inlegalllama_sft_pred_only_original_prompt_cross_bucket_fold00",
}
OUTPUTS = _HERE / "outputs"
ORDER = [
    "B0_majority",
    "B1_stratified",
    "B2_logreg_entity",
    "B3_svm_tfidf",
    "B4_logreg_tfidf",
    "B5_xgboost_entity",
    "B6_xgboost_tfidf_svd",
]


def load_llm_rows() -> dict[str, dict]:
    rows = {}
    for label, directory in LLM_RUNS.items():
        path = LLM_OUTPUTS / directory / "metrics.json"
        if not path.exists():
            continue
        metrics = json.loads(path.read_text())
        total = metrics.get("total_rows") or metrics.get("n_rows")
        parsed = metrics.get("parsed_rows")
        rows[label] = {
            "accuracy": float(metrics["accuracy"]),
            "macro_f1": float(metrics["macro_f1"]),
            "selective_accuracy": metrics.get("selective_accuracy"),
            "selective_macro_f1": metrics.get("selective_macro_f1"),
            "parse_rate": (parsed / total) if (parsed and total) else None,
        }
    return rows


def build_latex(summary: dict, hgt: dict, llm_rows: dict) -> str:
    baselines = summary["baselines"]
    majority = baselines["B0_majority"]["aggregate"]

    def row(label: str, features: str, accuracy: float, macro_f1: float, *, folds: str, bold: bool = False) -> str:
        d_majority = 100 * (accuracy - majority["accuracy_mean"])
        d_hgt = 100 * (hgt["accuracy_mean"] - accuracy)
        accuracy_cell = f"{100 * accuracy:.2f}"
        if bold:
            accuracy_cell = rf"\textbf{{{accuracy_cell}}}"
        return (
            f"{label} & {features} & {folds} & {accuracy_cell} & {macro_f1:.4f} & "
            f"{d_majority:+.2f} & " + ("---" if bold else f"{d_hgt:+.2f}") + r" \\"
        )

    lines = [
        r"% R3-03: non-LLM baselines on the identical five folds as the HGT run.",
        r"% Generated by Paper_Additional_Tests/codes/R3_03_non_llm_baselines/make_tables.py",
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{Non-LLM baselines on the identical five stratified folds used by \method{}."
        r" All models use the same retained PREAMBLE/FAC/argument source representation as the GNN;"
        r" TF--IDF additionally removes mask artifacts and direct operative-outcome vocabulary;"
        r" vectorisers, scalers and vocabularies are fit on training rows only and hyperparameters"
        r" are chosen on validation macro-F1. $\Delta$ maj.\ is the absolute gain over the"
        r" majority-class baseline; $\Delta$ HGT is \method{} minus the row, so a negative value"
        r" means the row is ahead of \method{}. LLM metrics use the full fold-0 denominator;"
        r" unparseable generations count as incorrect abstentions.}",
        r"\label{tab:non-llm-baselines}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\scriptsize",
        r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tabular}{l l c c c r r}",
        r"\toprule",
        r"Model & Features & Folds & Accuracy & Macro-F1 & $\Delta$ maj. & $\Delta$ HGT \\",
        r"\midrule",
    ]

    for name in ORDER:
        if name not in baselines or not baselines[name]["valid"]:
            continue
        entry = baselines[name]
        aggregate = entry["aggregate"]
        lines.append(
            row(entry["label"], entry["features"], aggregate["accuracy_mean"], aggregate["macro_f1_mean"],
                folds=str(entry["n_folds_completed"]))
        )

    lines.append(r"\midrule")
    for label, values in llm_rows.items():
        note = f"generative LLM, {100 * values['parse_rate']:.1f}\\% parsed" if values["parse_rate"] else "generative LLM"
        lines.append(row(label, note, values["accuracy"], values["macro_f1"], folds="1"))

    lines.append(r"\midrule")
    lines.append(
        row(r"\method{} (HGT)", "heterogeneous case graph", hgt["accuracy_mean"], hgt["macro_f1_mean"],
            folds="5", bold=True)
    )

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{adjustbox}", r"\end{table}"]
    return "\n".join(lines) + "\n"


SECTION_ORDER = ["preamble only", "facts only", "arguments only", "facts + arguments", "all three (fixed C)"]


def _section_decomposition(majority: dict, hgt: dict) -> list[str]:
    """Which rhetorical section carries the flat-text signal (section_ablation.py)."""
    path = OUTPUTS / "section_ablation.json"
    if not path.exists():
        return []
    sect = json.loads(path.read_text())
    base = majority["accuracy_mean"]
    rows = [
        f"| {key} | {100 * sect[key]['accuracy_mean']:.2f} ± {100 * sect[key]['accuracy_std']:.2f} "
        f"| {sect[key]['macro_f1_mean']:.4f} | {sect[key]['n_features']:,} "
        f"| {100 * (sect[key]['accuracy_mean'] - base):+.2f} "
        f"| {100 * (sect[key]['accuracy_mean'] - hgt['accuracy_mean']):+.2f} |"
        for key in SECTION_ORDER
        if key in sect
    ]
    lines = [
        "## Where the flat-text signal actually comes from",
        "",
        "Same folds, same sanitizer, same Linear SVM as B3 — only the sections given to TF-IDF change.",
        "This separates pre-decision case-type base rates (the preamble carries party names, court and",
        "petition type) from the case narrative (facts, arguments).",
        "",
        "| Sections used | Acc (%) | Macro-F1 | Features | Δ vs majority | Δ vs HGT |",
        "|---|---:|---:|---:|---:|---:|",
        *rows,
        "",
    ]
    pre = sect.get("preamble only", {}).get("accuracy_mean")
    nopre = sect.get("facts + arguments", {}).get("accuracy_mean")
    full = sect.get("all three (fixed C)", {}).get("accuracy_mean")
    if pre and nopre and full:
        lines += [
            f"**Reading.** The preamble alone reaches {100 * pre:.2f}% — {100 * (pre - base):+.2f} points over the",
            "majority class from party names, court and petition type, with no case narrative at all. That is a",
            "registry-level prior, the same shortcut family the paper's `no_names` ablation and identity-shortcut",
            "audits already police on the GNN side — so it is worth checking whether the flat-text baseline simply",
            "exploits it.",
            "",
            f"It does not. The preamble is largely redundant with the narrative: adding it on top of facts and",
            f"arguments is worth only {100 * (full - nopre):+.2f} points. Facts and arguments alone — every party",
            f"name, court and petition type stripped — already reach {100 * nopre:.2f}%,",
            f"{100 * (nopre - hgt['accuracy_mean']):+.2f} against the HGT.",
            "",
            "This matters for how the result is framed. The flat-text advantage is **not** an identity shortcut;",
            "it comes from the case narrative, which is precisely the evidence the graph model is supposed to",
            "reason over. The implication is that the frozen general-purpose text encoder, not the graph, is the",
            "binding constraint.",
            "",
        ]
    return lines


def build_report(summary: dict, hgt: dict, llm_rows: dict, build_report_json: dict) -> str:
    baselines = summary["baselines"]
    majority = baselines["B0_majority"]["aggregate"]
    valid = {n: e for n, e in baselines.items() if e["valid"] and n != "B0_majority" and n != "B1_stratified"}
    best_name = max(valid, key=lambda n: valid[n]["aggregate"]["accuracy_mean"]) if valid else None

    rows = []
    for name in ORDER:
        if name not in baselines:
            continue
        entry = baselines[name]
        aggregate = entry["aggregate"]
        rows.append(
            f"| {entry['label']} | {entry['features']} | "
            f"{100 * aggregate['accuracy_mean']:.2f} ± {100 * aggregate['accuracy_std']:.2f} | "
            f"{aggregate['macro_f1_mean']:.4f} ± {aggregate['macro_f1_std']:.4f} | "
            f"{100 * (aggregate['accuracy_mean'] - majority['accuracy_mean']):+.2f} | "
            f"{100 * (hgt['accuracy_mean'] - aggregate['accuracy_mean']):+.2f} |"
        )

    headline = []
    headline.append(
        f"- **Absolute improvement over the trivial baseline.** The majority-class baseline scores "
        f"{100 * majority['accuracy_mean']:.2f}% accuracy / {majority['macro_f1_mean']:.4f} macro-F1 "
        f"(the corpus is 60.8% positive). LegalGraph-LJP scores "
        f"{100 * hgt['accuracy_mean']:.2f}% / {hgt['macro_f1_mean']:.4f}, i.e. "
        f"**+{100 * (hgt['accuracy_mean'] - majority['accuracy_mean']):.2f} accuracy points and "
        f"+{hgt['macro_f1_mean'] - majority['macro_f1_mean']:.4f} macro-F1** over chance-level prediction."
    )
    if best_name:
        best = baselines[best_name]["aggregate"]
        delta = 100 * (hgt["accuracy_mean"] - best["accuracy_mean"])
        if delta >= 0:
            headline.append(
                f"- **Improvement over the strongest non-LLM baseline.** The best classical model is "
                f"{baselines[best_name]['label']} on {baselines[best_name]['features']} "
                f"({100 * best['accuracy_mean']:.2f}% / {best['macro_f1_mean']:.4f}). The GNN improves on it "
                f"by **{delta:+.2f} accuracy points / "
                f"{hgt['macro_f1_mean'] - best['macro_f1_mean']:+.4f} macro-F1**."
            )
        else:
            headline.append(
                f"- **⚠️ The strongest non-LLM baseline outperforms the GNN.** "
                f"{baselines[best_name]['label']} on {baselines[best_name]['features']} reaches "
                f"{100 * best['accuracy_mean']:.2f}% / {best['macro_f1_mean']:.4f}, i.e. "
                f"**{-delta:.2f} accuracy points above** LegalGraph-LJP's "
                f"{100 * hgt['accuracy_mean']:.2f}%. This is reported as found after the TF-IDF corpus "
                f"and fitted vocabulary both passed zero-tolerance checks for mask artifacts and direct "
                f"operative-outcome terms."
            )

    for label, values in llm_rows.items():
        headline.append(
            f"- For reference, {label} reaches {100 * values['accuracy']:.1f}% / {values['macro_f1']:.3f} "
            f"on the full denominator (unparseable generations count as incorrect abstentions)"
            + (
                f", with {100 * values['parse_rate']:.1f}% coverage and parsed-only diagnostic "
                f"{100 * values['selective_accuracy']:.1f}% / {values['selective_macro_f1']:.3f}."
                if values["parse_rate"] and values["selective_accuracy"] is not None
                else "."
            )
        )
    return "\n".join(
        [
            "# R3-03 — non-LLM baselines and the absolute improvement over a trivial baseline",
            "",
            "> *Reviewer 3: \"The paper compares against InLegalLlama (generative LLM) and text-only",
            "> ablations, but not against simpler baselines such as SVM on TF-IDF, Logistic Regression on",
            "> entity counts, or XGBoost. The absolute improvement over a trivial baseline is not shown.\"*",
            "",
            "## Protocol",
            "",
            f"All {summary['n_cases']:,} cases, the **same five folds as the HGT run** — read verbatim from",
            "its own `fold_XX/predictions.csv`, not re-derived. The five test folds were asserted at runtime",
            "to be pairwise disjoint and to cover the corpus exactly, and every cached label was checked",
            "against `predictions.csv` (0 mismatches).",
            "",
            "Features come from the **leakage-controlled cleaned cases the HGT itself consumes**:",
            "rhetorical roles `ANALYSIS/ISSUE/NONE/RATIO/RLC/RPC` already removed. Before TF-IDF, all",
            f"{build_report_json.get('leakage_mask_tokens_surviving_in_text', 0):,} surviving",
            "`[LEAKAGE_MASK]` artifacts and direct operative-outcome terms are removed. Runtime assertions",
            "require zero such terms in both the sanitized corpus and every fitted vocabulary.",
            "",
            "Per fold: vectorisers, scalers, SVD and authority vocabularies are fit on `split == \"train\"`",
            "rows only; the single regularisation hyperparameter is chosen on `split == \"val\"` macro-F1;",
            "`split == \"test\"` is scored once. Class weighting is on everywhere, matching the HGT's balanced",
            "cross-entropy. Metrics come from `section_GNN/src/training/metrics.py::compute_metrics`, the",
            "same function that produced the paper's numbers.",
            "",
            "Excluded as features by construction: `metadata.source_label_*` (literal copies of the label),",
            "`leakage_audit.dropped_sentence_role_counts` (an RPC-length proxy), and the entity fields",
            "`global_case_frequency` / `degree` / `is_shared_node` (corpus-level statistics computed over",
            "test cases).",
            "",
            "## Results (5-fold mean ± population s.d.)",
            "",
            "| Model | Features | Acc (%) | Macro-F1 | Δ vs majority | Δ vs HGT |",
            "|---|---|---:|---:|---:|---:|",
            *rows,
            f"| **LegalGraph-LJP (HGT, published)** | heterogeneous case graph | "
            f"**{100 * hgt['accuracy_mean']:.2f} ± {100 * hgt['accuracy_std']:.2f}** | "
            f"**{hgt['macro_f1_mean']:.4f} ± {hgt['macro_f1_std']:.4f}** | "
            f"+{100 * (hgt['accuracy_mean'] - majority['accuracy_mean']):.2f} | — |",
            "",
            "## Headline answers to the reviewer",
            "",
            *headline,
            "",
            *_section_decomposition(majority, hgt),
            "## Suggested change to the paper",
            "",
            "1. Add Table `tab:non-llm-baselines` and one paragraph stating the absolute gain over the",
            "   majority-class baseline and over the strongest classical model.",
            "2. Replace the old flat-text limitation with the result that the strongest TF-IDF model",
            "   exceeds HGT, while retaining the missing fine-tuned-transformer limitation.",
            "3. Do not include the raw-judgment oracle in the paper table; it contains decision text and",
            "   is not a valid baseline.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=OUTPUTS / "baselines_summary.json")
    args = parser.parse_args()

    summary = json.loads(args.summary.read_text())
    hgt = json.loads((REFERENCE_KFOLD / "kfold_summary.json").read_text())["aggregate"]
    llm_rows = load_llm_rows()
    build_report_json = json.loads((OUTPUTS / "features" / "build_report.json").read_text())

    (OUTPUTS / "table_r3_03_baselines.tex").write_text(build_latex(summary, hgt, llm_rows))
    (OUTPUTS / "report_r3_03.md").write_text(build_report(summary, hgt, llm_rows, build_report_json))
    print(f"wrote {OUTPUTS / 'table_r3_03_baselines.tex'}")
    print(f"wrote {OUTPUTS / 'report_r3_03.md'}")


if __name__ == "__main__":
    main()
